name = "Mahou!again"
author = "Dark_archer908"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7409a752009cbd9eeda958c98067cfdbd20d3a076320a10267e3316d08eed89c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
