name = "Mahou!again"
author = "Dark_archer908"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c63966e148b3dc0c22da3f5657846c4cd13f9171f3387caafe86582b3af9994"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
