name = "Mahou!again"
author = "Dark_archer908"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db758befa2ee49f46dc1ceae025dbdc930f1155f2fa20a6f5b84a209b1a50354"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
