name: discord message
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Actions for Discord
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        COMMIT_MSG: ${{ github.event.head_commit.message }}
      uses: Ilshidur/action-discord@0.4.0
      with:
        args: "$COMMIT_MSG"
