name: discord message
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: format commit msg
      env:
        RAW_MSG: ${{ github.event.head_commit.message }}
      run: |
        TITLE=$(echo "$RAW_MSG" | head -n 1)
        BODY=$(echo "$RAW_MSG" | tail -n +2 | sed -e '/./,$!d')
        EOF=$(dd if=/dev/urandom bs=15 count=1 2>/dev/null | base64 | tr -dc 'a-zA-Z0-9')
        echo "FORMATTED_MSG<<$EOF" >> $GITHUB_ENV
        if [ -z "$BODY" ]; then
          echo "**$TITLE**" >> $GITHUB_ENV
        else
          echo -e "**$TITLE**\n$BODY" >> $GITHUB_ENV
        fi
          echo "$EOF" >> $GITHUB_ENV
        
    - name: Actions for Discord
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@0.4.0
      with:
        args: "{{ FORMATTED_MSG }}"
